require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Naming/PredicateName:
  Exclude:
    - 'lib/darthjee/core_ext/object.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/support/shared_*/**/*.rb'

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/NestedGroups:
  Max: 5
