version: '2'
services:
  base: &base
    build:
      context: ./
    working_dir: /home/app/core_ext
    volumes:
      - .:/home/app/core_ext

  #################### CONTAINERS ####################

  core_ext:
    <<: *base
    container_name: core_ext
    command: bash -c 'bundle exec rspec'
