threshold: 91.2
require_exact_threshold: false
rules:
  ApiTag::Presence:
    enabled: true
    exclude: []
  ApiTag::Inclusion:
    enabled: true
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: true
    exclude: []
  ApiTag::PrivateMethod:
    enabled: true
    exclude: []
  ExampleTag:
    enabled: true
    exclude: []
  ReturnTag:
    enabled: true
    exclude:
      - Darthjee::CoreExt::Hash::KeyChanger#initialize
      - Darthjee::CoreExt::Array::HashBuilder#initialize
      - Darthjee::CoreExt::Hash::ChainFetcher#initialize
      - Darthjee::CoreExt::Array::HashBuilder#values
      - Darthjee::CoreExt::Array::HashBuilder#keys
      - Darthjee::CoreExt::Array::HashBuilder#values=
      - Darthjee::CoreExt::Array::HashBuilder#keys=
      - Darthjee::CoreExt::Hash::ChainFetcher#hash
      - Darthjee::CoreExt::Hash::ChainFetcher#keys
      - Darthjee::CoreExt::Hash::ChainFetcher#block
      - Darthjee::CoreExt::Hash::DeepHashConstructor#separator
      - Darthjee::CoreExt::Hash::DeepHashConstructor::Setter#hash
      - Darthjee::CoreExt::Hash::DeepHashConstructor::Setter#base_key
      - Darthjee::CoreExt::Hash::DeepHashConstructor::Setter#key
      - Darthjee::CoreExt::Hash::KeyChanger#hash
      - Darthjee::CoreExt::Hash::KeysSorter#hash
      - Darthjee::CoreExt::Hash::KeysSorter#recursive
      - Darthjee::CoreExt::Hash::Squasher#joiner
      - Darthjee::CoreExt::Hash::ValueChanger#recursive
      - Darthjee::CoreExt::Hash::ValueChanger#skip_inner
      - Darthjee::CoreExt::Hash::ValueChanger#block
  Summary::Presence:
    enabled: true
    exclude:
      - Darthjee::CoreExt::Hash::KeyChanger#initialize
      - Darthjee::CoreExt::Array::HashBuilder#initialize
      - Darthjee::CoreExt::Hash::ChainFetcher#initialize
      - Darthjee::CoreExt::Array::HashBuilder#values
      - Darthjee::CoreExt::Array::HashBuilder#keys
      - Darthjee::CoreExt::Array::HashBuilder#values=
      - Darthjee::CoreExt::Array::HashBuilder#keys=
      - Darthjee::CoreExt::Hash::ChainFetcher#hash
      - Darthjee::CoreExt::Hash::ChainFetcher#keys
      - Darthjee::CoreExt::Hash::ChainFetcher#block
      - Darthjee::CoreExt::Hash::DeepHashConstructor#separator
      - Darthjee::CoreExt::Hash::DeepHashConstructor::Setter#hash
      - Darthjee::CoreExt::Hash::DeepHashConstructor::Setter#base_key
      - Darthjee::CoreExt::Hash::DeepHashConstructor::Setter#key
      - Darthjee::CoreExt::Hash::KeyChanger#hash
      - Darthjee::CoreExt::Hash::KeysSorter#hash
      - Darthjee::CoreExt::Hash::KeysSorter#recursive
      - Darthjee::CoreExt::Hash::Squasher#joiner
      - Darthjee::CoreExt::Hash::ValueChanger#recursive
      - Darthjee::CoreExt::Hash::ValueChanger#skip_inner
      - Darthjee::CoreExt::Hash::ValueChanger#block
  Summary::Length:
    enabled: true
    exclude: []
  Summary::Delimiter:
    enabled: true
    exclude: []
  Summary::SingleLine:
    enabled: true
    exclude: []
