threshold: 84.5
require_exact_threshold: false
rules:
  ApiTag::Presence:
    enabled: true
    exclude: []
  ApiTag::Inclusion:
    enabled: true
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: true
    exclude: []
  ApiTag::PrivateMethod:
    enabled: true
    exclude: []
  ExampleTag:
    enabled: true
    exclude: []
  ReturnTag:
    enabled: true
    exclude:
      - Darthjee::CoreExt::Array::HashBuilder#initialize
      - Darthjee::CoreExt::Hash::ChainFetcher#initialize
      - Darthjee::CoreExt::Array::HashBuilder#values
      - Darthjee::CoreExt::Array::HashBuilder#keys
      - Darthjee::CoreExt::Array::HashBuilder#values=
      - Darthjee::CoreExt::Array::HashBuilder#keys=
      - Darthjee::CoreExt::Hash::ChainFetcher#hash
      - Darthjee::CoreExt::Hash::ChainFetcher#keys
      - Darthjee::CoreExt::Hash::ChainFetcher#block
  Summary::Presence:
    enabled: true
    exclude:
      - Darthjee::CoreExt::Array::HashBuilder#initialize
      - Darthjee::CoreExt::Hash::ChainFetcher#initialize
      - Darthjee::CoreExt::Array::HashBuilder#values
      - Darthjee::CoreExt::Array::HashBuilder#keys
      - Darthjee::CoreExt::Array::HashBuilder#values=
      - Darthjee::CoreExt::Array::HashBuilder#keys=
      - Darthjee::CoreExt::Hash::ChainFetcher#hash
      - Darthjee::CoreExt::Hash::ChainFetcher#keys
      - Darthjee::CoreExt::Hash::ChainFetcher#block
  Summary::Length:
    enabled: true
    exclude: []
  Summary::Delimiter:
    enabled: true
    exclude: []
  Summary::SingleLine:
    enabled: true
    exclude: []
